---
layout: cv
title: Alejandro Maurtua's CV
---
# Alejandro Maurtua
Business Finance student with Minor in Data Science.

<div id="webaddress">
<a href="alejandromaurtuap@gmail.com">alejandromaurtuap@gmail.com</a>
| <a href="https://www.linkedin.com/in/alejandro-maurtua/">My LinkedIn</a>
</div>



## Experience

### Data Manager Analyst Intern
Idaho Entrepeneur - Rexburg, ID - April 2024 - July 2024

•	Managed and cleaned data gathered by the project team to create competitive analysis reports comparing 20+ competitors from a new Chocolate business
•	Performed a Chocolate Taste test event and designed a professional questionnaire to compare the business product with 5 competitive brands
•	Analyzed and organized 180+ pages of data gathered from the Chocolate Taste test questionnaires to build visuals using PowerBI and provide insights and recommendations


### Hiring Assistant Analyst
BYU-I - Rexburg, ID - June 2022 - Current

•	Supervised and organized data from Business and Computer Science professionals applying for the Online Grader position using Microsoft Excel, Trello, Tableau, Workday, and BYU-I Management websites
•	Analyzed application documents including University/Master's transcripts for 100+ applicants each semester
•	Reviewed Digital Interviews from most qualified applicants to make final hiring decisions to fill out +15 vacancies each semester
•	Created final KPI reports using Microsoft Excel and compared performance with previous semesters


## Education

`2022-2026`
__BYU-Idaho, Rexburg.__

## GPA

`3.8`




## Scholarships

`Current`
BYU-I Scholarship




<!-- ### Footer

Last updated: May 2013 -->